### ISSUE TITLE
Low level information(input information) is getting outputted as an  intermediate representation

### ISSUE THREAD

**Issue by kumarnitish10m** [qir-alliance/qat#169]
Hi All,

I need one clarification as I am not sure whether the result I am getting is write or wrong. 
I have written similar code(DivisionByZeroPass) in my environment and tested and found some irregularities.  Therefore, I am looking for suggestion. 
(https://github.com/qir-alliance/qat/tree/main/qir/qat/Passes/DivisionByZeroPass)

My input ll(low level) is as below 
-----------------input file------------------
; entry point definition

define i64 @Entry_Point_Name() #0 {
entry:
  %0 = sdiv i64 10, 0
  br label %exit_block

exit_block:               ; preds = %entry
  ret i64 0
}
---------------------------end of input file---------------------

After running my binary (DivisionByZeroPass), I am getting below output

-----------------output information---------------------------

@qirerror_code = internal global i64 0

define i64 @Entry_Point_Name() {
entry:
  br i1 true, label %if_denominator_is_zero, label %after_zero_check

if_denominator_is_zero:                           ; preds = %entry
  %0 = load i64, i64* @qirerror_code, align 4
  %1 = icmp eq i64 %0, 0
  br i1 %1, label %if_ecc_not_set, label %ecc_set_finally

if_ecc_not_set:                                   ; preds = %if_denominator_is_zero
  store i64 1100, i64* @qirerror_code, align 4
  br label %ecc_set_finally

ecc_set_finally:                                  ; preds = %if_denominator_is_zero, %if_ecc_not_set
  br label %after_zero_check

after_zero_check:                                 ; preds = %entry, %ecc_set_finally
  %2 = sdiv i64 10, 0
  br label %exit_block

exit_block:                                       ; preds = %after_zero_check
  ret i64 0
}
------------------------------------------end of output-----------------

Question: Should QIR  print again ( %2 = sdiv i64 10, 0 ) after_zero_check block ? In general we don’t print input information in intermediate representation. 

I need suggestion from the community whether my understanding is write or wrong. What should I be doing in this case? 
I am looking forward to have either discussion or suggestion. 

Thanks & Regards,
Nitish

**Comment by swernli** [comment]
Glad to see you trying out code from the repo, @kumarnitish10m! I think there may be some confusion about what the purpose of the `DivideByZero` pass is and how it's expected to work. First off, it's part of the set of experimental passes, so should be considered prototype and not finalized. Currently, nothing uses this pass in any production scenarios that I'm aware of. The idea behind it was not to enable logic that skips the division, but rather add a check that ensures an error code gets set just before division takes place. At the time this code was first developed, the quantum systems we were targeting did not have any capability to halt an execution due to error and would always run the full program. As a result, the control systems would not exactly fail when dividing by zero but instead just produce an invalid result. The idea was to have a pass that injected code to check the division before it ran so that failure cases could be marked by an error code, and then fallthrough to the normal program execution afterward. That is the injected code you see:
```llvm
br i1 true, label %if_denominator_is_zero, label %after_zero_check

if_denominator_is_zero: ; preds = %entry
%0 = load i64, i64* @qirerror_code, align 4
%1 = icmp eq i64 %0, 0
br i1 %1, label %if_ecc_not_set, label %ecc_set_finally

if_ecc_not_set: ; preds = %if_denominator_is_zero
store i64 1100, i64* @qirerror_code, align 4
br label %ecc_set_finally

ecc_set_finally: ; preds = %if_denominator_is_zero, %if_ecc_not_set
br label %after_zero_check
```
It loads the global error value, and if no error code was already set, it will set one (the value `1100`). The first branch uses a hard-coded true because in this case constant folding has turned the check of the divisor value constant `0` into `true`. Finally, the execution branches to `%after_zero_check` which is the continuation of the original code:
```llvm
after_zero_check: ; preds = %entry, %ecc_set_finally
%2 = sdiv i64 10, 0
br label %exit_block

exit_block: ; preds = %after_zero_check
ret i64 0
```
And that is why you see the same instruction as in the input program here. So for now, the transformation pass is behaving as expected, though perhaps not as you were hoping it would.
